// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: download_history.sql

package dbgen

import (
	"context"
	"time"
)

const addDownloadHistory = `-- name: AddDownloadHistory :exec
INSERT INTO download_history (token_name, maya_version, ip_address, downloaded_at) VALUES (?, ?, ?, ?)
`

type AddDownloadHistoryParams struct {
	TokenName    string    `json:"token_name"`
	MayaVersion  *string   `json:"maya_version"`
	IpAddress    *string   `json:"ip_address"`
	DownloadedAt time.Time `json:"downloaded_at"`
}

func (q *Queries) AddDownloadHistory(ctx context.Context, arg AddDownloadHistoryParams) error {
	_, err := q.db.ExecContext(ctx, addDownloadHistory,
		arg.TokenName,
		arg.MayaVersion,
		arg.IpAddress,
		arg.DownloadedAt,
	)
	return err
}

const getDownloadHistory = `-- name: GetDownloadHistory :many
SELECT id, token_name, maya_version, ip_address, downloaded_at FROM download_history ORDER BY downloaded_at DESC LIMIT ?
`

type GetDownloadHistoryRow struct {
	ID           int64     `json:"id"`
	TokenName    string    `json:"token_name"`
	MayaVersion  *string   `json:"maya_version"`
	IpAddress    *string   `json:"ip_address"`
	DownloadedAt time.Time `json:"downloaded_at"`
}

func (q *Queries) GetDownloadHistory(ctx context.Context, limit int64) ([]GetDownloadHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDownloadHistoryRow{}
	for rows.Next() {
		var i GetDownloadHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.TokenName,
			&i.MayaVersion,
			&i.IpAddress,
			&i.DownloadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimDownloadHistory = `-- name: TrimDownloadHistory :exec
DELETE FROM download_history WHERE id NOT IN (
    SELECT id FROM download_history ORDER BY downloaded_at DESC LIMIT 100
)
`

func (q *Queries) TrimDownloadHistory(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, trimDownloadHistory)
	return err
}
