// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

import (
	"time"
)

type DownloadHistory struct {
	ID           int64     `json:"id"`
	TokenName    string    `json:"token_name"`
	MayaVersion  *string   `json:"maya_version"`
	DownloadedAt time.Time `json:"downloaded_at"`
}

type Migration struct {
	MigrationNumber int64     `json:"migration_number"`
	MigrationName   string    `json:"migration_name"`
	ExecutedAt      time.Time `json:"executed_at"`
}

type Session struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	Picture   *string   `json:"picture"`
}

type Token struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Token              string    `json:"token"`
	TokenType          string    `json:"token_type"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	MayaVersions       *string   `json:"maya_versions"`
	DefaultMayaVersion *string   `json:"default_maya_version"`
	SceneSettings      *string   `json:"scene_settings"`
	Requirements       *string   `json:"requirements"`
}

type UploadHistory struct {
	ID          int64     `json:"id"`
	FileName    string    `json:"file_name"`
	FileSize    int64     `json:"file_size"`
	UploadedAt  time.Time `json:"uploaded_at"`
	MayaVersion *string   `json:"maya_version"`
}

type Visitor struct {
	ID        string    `json:"id"`
	ViewCount int64     `json:"view_count"`
	CreatedAt time.Time `json:"created_at"`
	LastSeen  time.Time `json:"last_seen"`
}
