// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package dbgen

import (
	"context"
	"time"
)

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, email, picture, expires_at) VALUES (?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Picture   *string   `json:"picture"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Email,
		arg.Picture,
		arg.ExpiresAt,
	)
	return err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (name, token, token_type, maya_versions, default_maya_version, scene_settings) VALUES (?, ?, ?, ?, ?, ?) RETURNING id, name, token, token_type, maya_versions, default_maya_version, scene_settings, created_at, updated_at
`

type CreateTokenParams struct {
	Name               string  `json:"name"`
	Token              string  `json:"token"`
	TokenType          string  `json:"token_type"`
	MayaVersions       *string `json:"maya_versions"`
	DefaultMayaVersion *string `json:"default_maya_version"`
	SceneSettings      *string `json:"scene_settings"`
}

type CreateTokenRow struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Token              string    `json:"token"`
	TokenType          string    `json:"token_type"`
	MayaVersions       *string   `json:"maya_versions"`
	DefaultMayaVersion *string   `json:"default_maya_version"`
	SceneSettings      *string   `json:"scene_settings"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (CreateTokenRow, error) {
	row := q.db.QueryRowContext(ctx, createToken,
		arg.Name,
		arg.Token,
		arg.TokenType,
		arg.MayaVersions,
		arg.DefaultMayaVersion,
		arg.SceneSettings,
	)
	var i CreateTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.TokenType,
		&i.MayaVersions,
		&i.DefaultMayaVersion,
		&i.SceneSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const getAllTokens = `-- name: GetAllTokens :many
SELECT id, name, token, token_type, maya_versions, default_maya_version, scene_settings, created_at, updated_at FROM tokens ORDER BY token_type, name
`

type GetAllTokensRow struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Token              string    `json:"token"`
	TokenType          string    `json:"token_type"`
	MayaVersions       *string   `json:"maya_versions"`
	DefaultMayaVersion *string   `json:"default_maya_version"`
	SceneSettings      *string   `json:"scene_settings"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) GetAllTokens(ctx context.Context) ([]GetAllTokensRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllTokensRow{}
	for rows.Next() {
		var i GetAllTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Token,
			&i.TokenType,
			&i.MayaVersions,
			&i.DefaultMayaVersion,
			&i.SceneSettings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadTokens = `-- name: GetDownloadTokens :many
SELECT token FROM tokens WHERE token_type = 'download'
`

func (q *Queries) GetDownloadTokens(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, email, picture, created_at, expires_at FROM sessions WHERE id = ? AND expires_at > CURRENT_TIMESTAMP
`

type GetSessionRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Picture   *string   `json:"picture"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetSession(ctx context.Context, id string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Picture,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokenByName = `-- name: GetTokenByName :one
SELECT id, name, token, token_type, maya_versions, default_maya_version, scene_settings, created_at, updated_at FROM tokens WHERE name = ?
`

type GetTokenByNameRow struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Token              string    `json:"token"`
	TokenType          string    `json:"token_type"`
	MayaVersions       *string   `json:"maya_versions"`
	DefaultMayaVersion *string   `json:"default_maya_version"`
	SceneSettings      *string   `json:"scene_settings"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

func (q *Queries) GetTokenByName(ctx context.Context, name string) (GetTokenByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getTokenByName, name)
	var i GetTokenByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.TokenType,
		&i.MayaVersions,
		&i.DefaultMayaVersion,
		&i.SceneSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTokenNameByToken = `-- name: GetTokenNameByToken :one
SELECT name FROM tokens WHERE token = ?
`

func (q *Queries) GetTokenNameByToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRowContext(ctx, getTokenNameByToken, token)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUploadToken = `-- name: GetUploadToken :one
SELECT token FROM tokens WHERE token_type = 'upload' LIMIT 1
`

func (q *Queries) GetUploadToken(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getUploadToken)
	var token string
	err := row.Scan(&token)
	return token, err
}

const updateToken = `-- name: UpdateToken :exec
UPDATE tokens SET token = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTokenParams struct {
	Token string `json:"token"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken, arg.Token, arg.ID)
	return err
}
