// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package dbgen

import (
	"context"
	"time"
)

const cleanExpiredSessions = `-- name: CleanExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) CleanExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, email, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.ID, arg.Email, arg.ExpiresAt)
	return err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (name, token, token_type) VALUES (?, ?, ?) RETURNING id, name, token, token_type, created_at, updated_at
`

type CreateTokenParams struct {
	Name      string `json:"name"`
	Token     string `json:"token"`
	TokenType string `json:"token_type"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.Name, arg.Token, arg.TokenType)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.TokenType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE id = ?
`

func (q *Queries) DeleteToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteToken, id)
	return err
}

const getAllTokens = `-- name: GetAllTokens :many
SELECT id, name, token, token_type, created_at, updated_at FROM tokens ORDER BY token_type, name
`

func (q *Queries) GetAllTokens(ctx context.Context) ([]Token, error) {
	rows, err := q.db.QueryContext(ctx, getAllTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Token,
			&i.TokenType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDownloadTokens = `-- name: GetDownloadTokens :many
SELECT token FROM tokens WHERE token_type = 'download'
`

func (q *Queries) GetDownloadTokens(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDownloadTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT id, email, created_at, expires_at FROM sessions WHERE id = ? AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokenByName = `-- name: GetTokenByName :one
SELECT id, name, token, token_type, created_at, updated_at FROM tokens WHERE name = ?
`

func (q *Queries) GetTokenByName(ctx context.Context, name string) (Token, error) {
	row := q.db.QueryRowContext(ctx, getTokenByName, name)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Token,
		&i.TokenType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUploadToken = `-- name: GetUploadToken :one
SELECT token FROM tokens WHERE token_type = 'upload' LIMIT 1
`

func (q *Queries) GetUploadToken(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getUploadToken)
	var token string
	err := row.Scan(&token)
	return token, err
}

const updateToken = `-- name: UpdateToken :exec
UPDATE tokens SET token = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateTokenParams struct {
	Token string `json:"token"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateToken, arg.Token, arg.ID)
	return err
}
